---
plugins:
  # https://github.com/babel/eslint-plugin-babel
  - react

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  node: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - "eslint:recommended"
  - "plugin:react/recommended"

rules:
  no-console: 0
  no-alert: 0
  spaced-comment: 0
  react/jsx-uses-react: error
  react/jsx-uses-vars: error

settings: 
  react: 
    version: detect