---
plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  - import
  - prettier

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  node: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - "airbnb-base"
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "prettier"

rules:
  no-console: 0
  no-alert: 0
  spaced-comment: 0
  prettier/prettier: error
